spring:
  application:
    name: fitinside
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

  # H2 DB 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fitinside
    username: sa
    password: ''

  # H2 console 설정
  h2:
    console:              # h2 DB를 웹에서 관리할 수 있는 기능
      enabled: true       # h2 console 사용 여부
      path: /h2-console   # h2 console 접속 주소

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: create    # DB 초기화 전략
    properties:
      hibernate:
        format_sql: true  # 쿼리 로그 포맷 (저렬)
        show_sql: true    # 쿼리 로그 출력
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_ID}
            client-secret: ${GOOGLE_OAUTH_PW}
            scope:
              - email
              - profile

  # 메일 SMTP 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: chm20060
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucketName: fitinside
    region:
      static: ap-northeast-2
    stack:
      auto: false